### ISSUE TITLE
Color Picker disables Hot Corner abilities  

### ISSUE THREAD

**Issue by mittelgrau** [sindresorhus/System-Color-Picker#10]
MacOs Version: Big Sur 11.3.1  

As the title states I can't drag and drop any items when "show Desktop" is activated via hot corner.

**Comment by sindresorhus** [comment]
Can you elaborate? How exactly does this app disable "hot corners"?

**Comment by mittelgrau** [comment]
Sorry for keeping it so brief. I‘ve set my lower left corner to a hot corner which shows my desktop. While the color picker runs i can‘t drag and drop or interact with any file/ folder on the visible desktop. As i close the app the behaviour runs as expected. Cursor to the lower left, desktop Shows and i can interact with every file.

**Comment by sindresorhus** [comment]
There's an update out that fixes this: https://apps.apple.com/no/app/system-color-picker/id1545870783?mt=12
