### ISSUE TITLE
Make LCH not clamped to sRGB

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/System-Color-Picker#13]
Currently, the LCH color is clamped to sRGB as the browser support for high gamut is limited. I think we could add a preference later on to enable high gamut LCH. Is a preference even needed? Could we make high gamut the default at some point?

How will browsers handle this?

**Comment by KyleErhabor** [comment]
Since May 15th, [all major browsers have supported LCH](https://caniuse.com/css-lch-lab). Personally, I think making the copy button support right clicking to select the color space to use ("Copy as sRGB" vs. "Copy as ) would be good.

**Comment by naiyerasif** [comment]
With [color-gamut](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut) media query, wide color gamut can be progressively adopted in browsers. Hence, a preference to remove the clamp to sRGB would be great.
