### ISSUE TITLE
 Quit shortcuts and menus are missing. The white dot disappears.

### ISSUE THREAD

**Issue by hazarek** [sindresorhus/System-Color-Picker#17]
When I look at the dock, it is not clear whether the application is open or not on Dock icon. The white dot disappears.

https://user-images.githubusercontent.com/36481442/137536436-156570ff-6aff-4a0e-b501-2bb679134f53.mov

--- 
Also application does not appear in the quick switch interface. Command+Tab | Comman+Q.

![tutorials-9832-0-70764300-1594797311_thumb](https://user-images.githubusercontent.com/36481442/137537782-5e4cb402-d3d4-477a-a0d8-73e885660a7a.jpg)

There is no Quit option when right clicked on the Dock icon.

<img width="234" alt="Ekran Resmi 2021-10-15 21 55 26" src="https://user-images.githubusercontent.com/36481442/137538519-1c45ffae-b77d-438b-bc6a-e239ef3f68dd.png">

**Comment by sindresorhus** [comment]
Weird issue and I cannot reproduce. What exact macOS version are you on?

**Comment by hazarek** [comment]
> Weird issue and I cannot reproduce. What exact macOS version are you on? Can you try restarting your computer and see if the issue persists?

macOS BigSur 11.6 (20G165) I restarted the system and it didn't fix it.

**Comment by sindresorhus** [comment]
Alright. I figured out what's going on. You had `Keep in Dock` enabled on the Dock icon and then enabled the `Show in menu bar` setting. However, the `Show in menu bar` setting, means it will no longer work from the Dock. There's also no way to automatically remove the Dock icon if you have `Keep in Dock` enabled.

I will make the setting name clearer in the next version.
