### ISSUE TITLE
HSB/HSV color model support

### ISSUE THREAD

**Issue by hazarek** [sindresorhus/System-Color-Picker#18]
I want to copy the color as HSB but it is only available as HSL.

<img width="341" alt="Ekran Resmi 2021-10-27 21 52 58" src="https://user-images.githubusercontent.com/36481442/139128933-6c0ffd03-b7c8-4a15-b71c-ed93b12db130.png">

**Comment by sindresorhus** [comment]
CSS does not support HSB.

I'm curious what you're using HSB for? HSL is more human-friendly and much more widespread.

I have plans to add HSL and LCH sliders. Just haven't gotten around to it yet.

**Comment by hazarek** [comment]
> CSS does not support HSB.
> 
> I'm curious what you're using HSB for? HSL is more human-friendly and much more widespread.
> 
> I have plans to add HSL and LCH sliders. Just haven't gotten around to it yet.

It was needed for [p5.js](https://p5js.org/reference/#/p5/HSB). Easier to memorize than HSL. Also Apple Motion uses HSV/HSB color model

> I'm curious what you're using HSB for? HSL is more human-friendly and much more widespread

According to what statistic? I think HSV/HSB better than HSL. CSS is a language for web developers only. This is a desktop application.

**Comment by sindresorhus** [comment]
> CSS is a language for web developers only.

Yes, but web developers is the largest audience.

**Comment by sindresorhus** [comment]
Alright. I will add HSB.

**Comment by sindresorhus** [comment]
Added in https://github.com/sindresorhus/System-Color-Picker/releases/tag/v1.9.0

<img width="281" alt="Screen Shot 2021-11-13 at 13 59 50" src="https://user-images.githubusercontent.com/170270/141609389-27f48778-9f02-464a-b1a4-44367464205c.png">
