### ISSUE TITLE
when pasting in a hex color, the palette changes but the text field does not

### ISSUE THREAD

**Issue by luckman212** [sindresorhus/System-Color-Picker#23]
- macOS 12.1
- SCP v1.9.0 (MAS)

#### Repro
- If you put `ff4915` in your pasteboard, and enter the hex field and press <kbd>⌘cmd+V</kbd> the color wheel & swatch will update but the field (usually) remains at its previous value
- bonus: _sometimes_ the field _does_ update after pasting. This usually happens after fiddling with the controls a bit. 

here's a screen recording:

https://user-images.githubusercontent.com/1992842/148231395-eaa8d661-c30a-41c0-9433-d73bcdee34c9.mp4

**Comment by sindresorhus** [comment]
Turns out this is a bug in macOS 12. I'll get out a fix shortly.

**Comment by sindresorhus** [comment]
The update is out: https://apps.apple.com/no/app/system-color-picker/id1545870783?mt=12

**Comment by luckman212** [comment]
Awesome! I looked at the commit, that was a whole lot of work to work around this little bug. Thank you!
