### ISSUE TITLE
Add Support for Localization

### ISSUE THREAD

**Issue by isametry** [sindresorhus/System-Color-Picker#24]
Although the app obviously isn't very text-heavy, I think it would be neat to allow contributors to translate Color Picker into other languages.

The app already feels 95% like a native Mac app, and having the app name and menu options in my own language (not English) would make that 100%.

Apple's instructions for app localization can be found here: https://developer.apple.com/documentation/xcode/localization

**Comment by sindresorhus** [comment]
I don't have any immediate plans to localize the app. Localization creates a **lot** of overhead and extra work (more than you imagine) and it's not something I can commit to for a free app I made for fun in my spare time.
