### ISSUE TITLE
OKLCH color support

### ISSUE THREAD

**Issue by aaronkollasch** [sindresorhus/System-Color-Picker#29]
Can you add support for OKLCH colors? [OKLCH](https://bottosson.github.io/posts/oklab/) has been added to CSS color 4 and is superior to LCH, particularly at perceptually uniform blending of colors without [hue shifts](https://bottosson.github.io/posts/oklab/#blending-colors).

Browser support isn't [here yet](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch), so no rush, but I think OKLCH will be better than LCH when you get to implementing color sliders #20.

**Comment by sindresorhus** [comment]
Yeah. Will do at some point.
