### ISSUE TITLE
Request for Homebrew Support

### ISSUE THREAD

**Issue by ProfessorManhattan** [sindresorhus/System-Color-Picker#32]
Hey, can you please publish a Homebrew Cask for this (and possibly all your other products as well)? You have a lot of amazing apps but none of them are available on `brew` which is a requirement for headless installs. I'm trying to include this app in https://install.doctor.

Alternatively, maybe you can add a one-line bash command that installs the app in the README.md?

**Comment by sindresorhus** [comment]
Sorry. No plans to add my apps to Homebrew. Releasing in multiple places requires continuous extra effort and there's just not enough demand to warrant doing that.
