### ISSUE TITLE
The app does not show up in the menu bar - solution

### ISSUE THREAD

**Issue by ukushu** [sindresorhus/System-Color-Picker#34]
>The app does not show up in the menu bar
>macOS hides menu bar apps when there is no space left in the menu bar. This is a common problem on MacBooks with a notch. Try quitting some menu bar apps to free up space. If this does not solve it, try quitting Bartender if you have it installed.

You can sort icons in MenuBar using Cmd button + mouse.

No need to use any extra soft like Bartender. Just move app to the right corner of Menubar :)

**Comment by sindresorhus** [comment]
I don't think you are fully understanding what the text is saying. It's about what to do if you cannot see the menu bar item in the menu bar. It's not a recommendation to use Bartender.
