### ISSUE TITLE
Unable to change the text fields unless settings open

### ISSUE THREAD

**Issue by BigEmperor26** [sindresorhus/System-Color-Picker#35]
Great app and work man!

I just noticed that there is this bug, where the text fields are not responsive. I can change the colours using the palette and the picker, but unable to change the exact values in the text fields, unless i have the color picker settings open. Only then the field becomes available to edit. Using Sonoma currently, on 

I was wondering if this could be fixed somehow. Unfortunately I am not experienced with Swift and X Code and I cannot find the issue by myself.

**Comment by sindresorhus** [comment]
This was already fixed in yesterday's update (1.14.0).
