### ISSUE TITLE
Allowing picking P3 Colors

### ISSUE THREAD

**Issue by Oneechan69** [sindresorhus/System-Color-Picker#36]
There doesn't seem to be any Mac color pickers that support P3 colors. if I pick a P3 color in Safari (which supports P3 colors out of the box) it will just output the color in SRGB color formats. Safari has its own built-in P3 color picker:
<img width="1496" alt="Screenshot 2023-12-20 at 2 01 53 PM" src="https://github.com/sindresorhus/System-Color-Picker/assets/42647030/e13a71dd-2f6c-40fd-8842-6bb1ef45fa79">

**Comment by sindresorhus** [comment]
Display P3 is a good format for screens, but not for humans. I recommend using LCH, which has the range of Display P3, but in a more human-friendly format. OKLCH is even better, and something I plan to support soon.

**Comment by Oneechan69** [comment]
What do you mean by not for humans? The color picker could show P3 values like with the CSS `color()` function, and it could be used to tell if a color you defined is a P3 color or not.

**Comment by sindresorhus** [comment]
I recommend reading: https://www.smashingmagazine.com/2023/08/oklch-color-spaces-gamuts-css/
