### ISSUE TITLE
Custom Palettes 

### ISSUE THREAD

**Issue by mgunville** [sindresorhus/System-Color-Picker#39]
I love the ability to select colors and add them directly to the macOS 'other colors' picker used by other products.  That said, I work with multiple clients, and it would be really helpful to have the option to create individual palettes for each brand so I can keep the blue from Client 1 separate from the blue from Client 2.  

Would you be willing to add an option to save and access custom palettes within the app?  Ideally, there would be a 6th icon across the top row that changes the color wheel/crayons/etc. to a series of rows with up to 4 most recent custom palettes that include color blocks that can be dragged to the system set on the bottom.  A context-specific menu row that includes [+], [-] and [trash] icons would allow users to create/delete palettes and trash individual colors from a given palette without cluttering the screen. 

If this isn't an option, an option with more clicks would leverage your existing Palettes icon to the left of the [...] button on your menu bar in the middle of the panel.  An option to add new palettes here would be useful, though selecting the palette to save a given color to, and remove from, will require more effort. 

This could also be a one time purchase option to compensate for the extra functionality.  

---

**Comment by sindresorhus** [comment]
Custom palettes are already supported: https://github.com/sindresorhus/System-Color-Picker?tab=readme-ov-file#how-do-i-use-palettes
