### ISSUE TITLE
Scala should be spelled Skala and is "paused" so suggest removing refs to it

### ISSUE THREAD

**Issue by Touchgram** [sindresorhus/System-Color-Picker#40]
Your docs refer to the Skala Color plugin as "Scala".

Also, checking their site https://bjango.com/mac/skalacolor/ it says

> Skala Color is on hold for now
> There are some bugs in Skala Color that we don’t think we can fix while keeping it a macOS color picker.

**Comment by sindresorhus** [comment]
I'm using it and it works fine even though it's not actively maintained.
