### ISSUE TITLE
accessibility color name not updating

### ISSUE THREAD

**Issue by ParkerCai** [sindresorhus/System-Color-Picker#41]
Love this app! It's almost perfect however there's a bug for the "Show accessibility color name" feature. It only works on the first time right after toggled on. The name of the color won't update subsequently when new color is picked. Maybe the state is not updating when new changes detected? 

---

**Comment by sindresorhus** [comment]
Fixed in the latest update: https://github.com/sindresorhus/System-Color-Picker/releases/tag/v2.0.1

**Comment by ParkerCai** [comment]
Awesome! Thanks for updating it.
