### ISSUE TITLE
What code is used to create the Opacity slider?

### ISSUE THREAD

**Issue by Nickno95** [sindresorhus/System-Color-Picker#44]
In the main window, there is an opacity slider that has tick marks for 0%, 50%, and 100%. 

<img width="271" alt="Screenshot 2024-06-14 at 5 10 32 PM" src="https://github.com/sindresorhus/System-Color-Picker/assets/11400284/de243550-d8e4-41ca-ab21-00bc5c1508cc">

Would like to know how this was achieved and where it is in the project. Is it using UISlider, SwiftUI Slider, NSSlider, custom, something else? 

Trying to learn how it has both tick marks that the slider snaps to and able to still continuously slide.

**Comment by sindresorhus** [comment]
This is not the place to ask Mac app development questions. The slider is provided by macOS and not the app itself, so I cannot answer this regardless.
