### ISSUE TITLE
LCH color support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/System-Color-Picker#5]
I plan to add support for [LCH color](https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/) (not Lab since it's almost the same, just not as human-friendly). It's superior to HSL and RGB.

There's no rush though. Doesn't seem like all browsers support it yet: https://chromestatus.com/feature/4592567062626304

**Comment by svgeesus** [comment]
Nice!

On browser support, Safari Technical Preview 123 supports it. Chrome and Firefox are looking into it.
