### ISSUE TITLE
Automatically copy to clipboard

### ISSUE THREAD

**Issue by Clock-Drift** [sindresorhus/System-Color-Picker#7]
It could be useful to automatically copy the picked value to the clipboard based on a pre-defined preference rather than have to copy using the keyboard shortcut. I can imagine this will differ depending on whether the user needs HEX, RGB, etc. but it would lead to a smoother workflow, especially when integrating with launchers like Raycast (example attached)

https://user-images.githubusercontent.com/48359410/117535038-d6bfc700-afeb-11eb-883a-33bad5ddd7cc.mp4

**Comment by sindresorhus** [comment]
I agree. Something like this would be useful. I considered it initially, but was not sure how to handle it. Should the user select in the preferences which format they want copied? How should it work?

**Comment by Clock-Drift** [comment]
Previous pickers I've used have defaulted to HEX, but I do think user-selectable in preferences is optimal. Something like a 'Preferred format' option with a pull-down/pop-up button could work perfectly

**Comment by sindresorhus** [comment]
I tried the latter. Seems to be working:

<img width="368" alt="Screen Shot 2021-05-11 at 21 35 43" src="https://user-images.githubusercontent.com/170270/117833806-d865e500-b2a0-11eb-8253-b2983f1b0ac2.png">
