### ISSUE TITLE
'Show colour sampler when opening window' does not work in menu bar mode unless clicked 

### ISSUE THREAD

**Issue by Clock-Drift** [sindresorhus/System-Color-Picker#8]
Opening the picker via a launcher shortcut (Raycast/Spotlight) fails when in menu bar mode

https://user-images.githubusercontent.com/48359410/117534954-821c4c00-afeb-11eb-9795-7ab683b2b0b3.mp4

**Comment by sindresorhus** [comment]
Why have it in the menu bar if you're just going to launch/activate it with an app launcher?

**Comment by Clock-Drift** [comment]
Initially this was a use case quirk due to speed concerns (didn't want to have to wait to open each time I needed it) but actually I'm finding there is absolutely no delay when opening cold from applications, so this could be considered resolved!
